// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("comment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1L,
                            Text = "Glad to be here!",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1L,
                            Text = "me too!",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1L,
                            Text = "Yippee!",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2L,
                            Text = "Cool",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2L,
                            Text = "as sakau",
                            UserId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3L,
                            Text = "neidomu",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("Backend.Entities.Community", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("community", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Community for tech enthusiasts",
                            Name = "TechTalks",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreationDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Community for antiem zmonem",
                            Name = "AntrasCommunity",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Backend.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CommunityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("post", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CommunityId = 1L,
                            CreationDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "First post 🎉",
                            Title = "Welcome!",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CommunityId = 1L,
                            CreationDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "SecondPost",
                            Title = "Second!",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CommunityId = 2L,
                            CreationDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "ThirdPost",
                            Title = "Third!",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            CommunityId = 1L,
                            CreationDate = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Text = "ThirdPost",
                            Title = "Third!",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("app_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Blocked = false,
                            Email = "admin@example.com",
                            Name = "Admin",
                            Password = "adminpassword",
                            RoleId = 1L,
                            Surname = "User",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            Blocked = false,
                            Email = "saras@example.com",
                            Name = "Saras",
                            Password = "saras",
                            RoleId = 2L,
                            Surname = "saras",
                            Username = "saras"
                        },
                        new
                        {
                            Id = 3L,
                            Blocked = false,
                            Email = "user1@example.com",
                            Name = "user1",
                            Password = "user1",
                            RoleId = 2L,
                            Surname = "user1",
                            Username = "user1"
                        });
                });

            modelBuilder.Entity("Backend.Entities.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("user_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("Backend.Entities.Comment", b =>
                {
                    b.HasOne("Backend.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.Community", b =>
                {
                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("Communities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.Post", b =>
                {
                    b.HasOne("Backend.Entities.Community", "Community")
                        .WithMany("Posts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.HasOne("Backend.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Entities.Community", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Backend.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Backend.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Communities");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Backend.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
